# Generated by Django 3.2.19 on 2023-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allowed_categories',
            field=models.ManyToManyField(blank=True, to='core.Category', verbose_name='Доступные категории'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Менеджер'), (2, 'Администратор')], default=1, verbose_name='Роль'),
        ),
    ]
