# Generated by Django 3.2.19 on 2023-05-07 17:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230507_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='article',
            field=models.CharField(max_length=128, unique=True, verbose_name='Артикул товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Наименование'),
        ),
    ]
